version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gofmt
    - goimports
    - gosec

formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/iszlai/chamele-go

issues:
  exclude-dirs:
    - vendor
  exclude:
    - path: _test\.go
      linters:
        - gosec
